### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by 8eecf0d2** [dfmcphee/simplifeed#1]
Looks promising, been playing around and it's very slick so far.

Any roadmap planned? I'd love to see s3 dropped personally

**Comment by dfmcphee** [comment]
Glad you like it so far. I am planning on adding alternate configs for the storage. I created a public Trello board that I will be updating as I go.

https://trello.com/b/VAl8u16c/simplifeed

**Comment by 8eecf0d2** [comment]
Thanks!
