### ISSUE TITLE
Problems getting started.

### ISSUE THREAD

**Issue by klynton** [dfmcphee/simplifeed#2]
Hi,

I tried this out by following the README - https://github.com/dfmcphee/simplifeed#getting-started

The app fails to start because I don't have a Twitter access key, if I remove the Twitter config it asks for Facebook or Yammer. I've looked at the library you are using for auth, Passport, and it seems to have a method for local authentication but there's no implementation for it.

Is there a way to get started that doesn't require me having a Twitter app ID, Facebook App ID, and Yammer app ID?

Once I removed Twitter and Yammer, created the Facebook ID, and set up S3 and the mailer configuration I got a 500 error because the DB hadn't been created. I had to run `geddy jake db:migrate` (which wasn't listed in the instructions).

**Comment by klynton** [comment]
A couple other things I noted after getting it working:
- A post is a varchar(255) so if you paste in multiple lines it will crash the process
- The `ejs` module will frequently stop being found despite no changes to the directory structure.

**Comment by dfmcphee** [comment]
Thank you for your comments. I have updated the read me and started the wiki with more information on how to get setup. You will no longer need the Facebook, Twitter, or Yammer API keys.

That is a good point about the post content being a varchar. I am going to create a new issue for that.

**Comment by klynton** [comment]
Awesome, thank you!
